### ISSUE TITLE
ERROR: (k) <= (probs.size())?

### ISSUE THREAD

**Issue by duyhtq** [sh1r0/caffe-android-demo#8]
hi. i got the imagenet sample model works fine.  but when i tried to plug in my own model, i got the following error, and the prediction isn't correct as supposed.  any idea what this error is?  thanks.

10-28 13:56:52.274    8767-8840/com.sh1r0.caffe_android_demo D/stderr﹕ [ 10-28 13:56:52.274  8767: 8840 D/stderr   ]
    [
10-28 13:56:52.274    8767-8840/com.sh1r0.caffe_android_demo D/stderr﹕ ERROR
10-28 13:56:52.274    8767-8840/com.sh1r0.caffe_android_demo D/stderr﹕ ]
10-28 13:56:52.274    8767-8840/com.sh1r0.caffe_android_demo D/stderr﹕ (k) <= (probs.size())
10-28 13:56:52.274    8767-8840/com.sh1r0.caffe_android_demo D/stderr﹕ [ 10-28 13:56:52.274  8767: 9244 D/MiRA-CNN ]

**Comment by sh1r0** [comment]
Please refer to [caffe_mobile.cpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_mobile.cpp) and [caffe_jni.cpp](https://github.com/sh1r0/caffe-android-lib/blob/master/caffe-mobile/jni/caffe_jni.cpp). Since the jni interface is for demo purpose, I just hardcoded k = 3 for getting top-3 predictions. The error might be caused by the output size of your network, which is possibly less than 3.

**Comment by duyhtq** [comment]
ahh ok.  i'm building a binary classification so i guess i just need to change the number 3 below to 2?

but either way, this shouldn't change the result right?  b/c you return the first one top_k[0] anyway?

```
jint JNIEXPORT JNICALL
Java_com_sh1r0_caffe_1android_1demo_CaffeMobile_predictImage(JNIEnv* env, jobject thiz, jstring imgPath)
{
    const char *img_path = env->GetStringUTFChars(imgPath, 0);
    caffe::vector<int> top_k = caffe_mobile->predict_top_k(string(img_path), 3);
    LOGD("top-1 result: %d", top_k[0]);

    env->ReleaseStringUTFChars(imgPath, img_path);

    return top_k[0];
}
```

**Comment by sh1r0** [comment]
Yes.
